package com.example.emailmanager.data;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCESSORY_DETAIL".
*/
public class AccessoryDetailDao extends AbstractDao<AccessoryDetail, Long> {

    public static final String TABLENAME = "ACCESSORY_DETAIL";

    /**
     * Properties of entity AccessoryDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FileName = new Property(1, String.class, "fileName", false, "FILE_NAME");
        public final static Property Path = new Property(2, String.class, "path", false, "PATH");
        public final static Property Size = new Property(3, String.class, "size", false, "SIZE");
        public final static Property Total = new Property(4, long.class, "total", false, "TOTAL");
        public final static Property IsDownload = new Property(5, boolean.class, "isDownload", false, "IS_DOWNLOAD");
        public final static Property EmailId = new Property(6, Long.class, "emailId", false, "EMAIL_ID");
    }

    private Query<AccessoryDetail> emailDetail_AccessoryListQuery;

    public AccessoryDetailDao(DaoConfig config) {
        super(config);
    }
    
    public AccessoryDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCESSORY_DETAIL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILE_NAME\" TEXT," + // 1: fileName
                "\"PATH\" TEXT," + // 2: path
                "\"SIZE\" TEXT," + // 3: size
                "\"TOTAL\" INTEGER NOT NULL ," + // 4: total
                "\"IS_DOWNLOAD\" INTEGER NOT NULL ," + // 5: isDownload
                "\"EMAIL_ID\" INTEGER);"); // 6: emailId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCESSORY_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AccessoryDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(2, fileName);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
 
        String size = entity.getSize();
        if (size != null) {
            stmt.bindString(4, size);
        }
        stmt.bindLong(5, entity.getTotal());
        stmt.bindLong(6, entity.getIsDownload() ? 1L: 0L);
 
        Long emailId = entity.getEmailId();
        if (emailId != null) {
            stmt.bindLong(7, emailId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AccessoryDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(2, fileName);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
 
        String size = entity.getSize();
        if (size != null) {
            stmt.bindString(4, size);
        }
        stmt.bindLong(5, entity.getTotal());
        stmt.bindLong(6, entity.getIsDownload() ? 1L: 0L);
 
        Long emailId = entity.getEmailId();
        if (emailId != null) {
            stmt.bindLong(7, emailId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AccessoryDetail readEntity(Cursor cursor, int offset) {
        AccessoryDetail entity = new AccessoryDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // fileName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // path
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // size
            cursor.getLong(offset + 4), // total
            cursor.getShort(offset + 5) != 0, // isDownload
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // emailId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AccessoryDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFileName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSize(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTotal(cursor.getLong(offset + 4));
        entity.setIsDownload(cursor.getShort(offset + 5) != 0);
        entity.setEmailId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AccessoryDetail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AccessoryDetail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AccessoryDetail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "accessoryList" to-many relationship of EmailDetail. */
    public List<AccessoryDetail> _queryEmailDetail_AccessoryList(Long emailId) {
        synchronized (this) {
            if (emailDetail_AccessoryListQuery == null) {
                QueryBuilder<AccessoryDetail> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.EmailId.eq(null));
                emailDetail_AccessoryListQuery = queryBuilder.build();
            }
        }
        Query<AccessoryDetail> query = emailDetail_AccessoryListQuery.forCurrentThread();
        query.setParameter(0, emailId);
        return query.list();
    }

}
