package com.example.emailmanager.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.emailmanager.data.Email;
import com.example.emailmanager.data.AccountDetail;

import com.example.emailmanager.data.EmailDao;
import com.example.emailmanager.data.AccountDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emailDaoConfig;
    private final DaoConfig accountDetailDaoConfig;

    private final EmailDao emailDao;
    private final AccountDetailDao accountDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emailDaoConfig = daoConfigMap.get(EmailDao.class).clone();
        emailDaoConfig.initIdentityScope(type);

        accountDetailDaoConfig = daoConfigMap.get(AccountDetailDao.class).clone();
        accountDetailDaoConfig.initIdentityScope(type);

        emailDao = new EmailDao(emailDaoConfig, this);
        accountDetailDao = new AccountDetailDao(accountDetailDaoConfig, this);

        registerDao(Email.class, emailDao);
        registerDao(AccountDetail.class, accountDetailDao);
    }
    
    public void clear() {
        emailDaoConfig.clearIdentityScope();
        accountDetailDaoConfig.clearIdentityScope();
    }

    public EmailDao getEmailDao() {
        return emailDao;
    }

    public AccountDetailDao getAccountDetailDao() {
        return accountDetailDao;
    }

}
