package com.example.emailmanager.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.emailmanager.data.Email;
import com.example.emailmanager.data.AccountDetail;
import com.example.emailmanager.data.EmailDetail;
import com.example.emailmanager.data.AccessoryDetail;

import com.example.emailmanager.data.EmailDao;
import com.example.emailmanager.data.AccountDetailDao;
import com.example.emailmanager.data.EmailDetailDao;
import com.example.emailmanager.data.AccessoryDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emailDaoConfig;
    private final DaoConfig accountDetailDaoConfig;
    private final DaoConfig emailDetailDaoConfig;
    private final DaoConfig accessoryDetailDaoConfig;

    private final EmailDao emailDao;
    private final AccountDetailDao accountDetailDao;
    private final EmailDetailDao emailDetailDao;
    private final AccessoryDetailDao accessoryDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emailDaoConfig = daoConfigMap.get(EmailDao.class).clone();
        emailDaoConfig.initIdentityScope(type);

        accountDetailDaoConfig = daoConfigMap.get(AccountDetailDao.class).clone();
        accountDetailDaoConfig.initIdentityScope(type);

        emailDetailDaoConfig = daoConfigMap.get(EmailDetailDao.class).clone();
        emailDetailDaoConfig.initIdentityScope(type);

        accessoryDetailDaoConfig = daoConfigMap.get(AccessoryDetailDao.class).clone();
        accessoryDetailDaoConfig.initIdentityScope(type);

        emailDao = new EmailDao(emailDaoConfig, this);
        accountDetailDao = new AccountDetailDao(accountDetailDaoConfig, this);
        emailDetailDao = new EmailDetailDao(emailDetailDaoConfig, this);
        accessoryDetailDao = new AccessoryDetailDao(accessoryDetailDaoConfig, this);

        registerDao(Email.class, emailDao);
        registerDao(AccountDetail.class, accountDetailDao);
        registerDao(EmailDetail.class, emailDetailDao);
        registerDao(AccessoryDetail.class, accessoryDetailDao);
    }
    
    public void clear() {
        emailDaoConfig.clearIdentityScope();
        accountDetailDaoConfig.clearIdentityScope();
        emailDetailDaoConfig.clearIdentityScope();
        accessoryDetailDaoConfig.clearIdentityScope();
    }

    public EmailDao getEmailDao() {
        return emailDao;
    }

    public AccountDetailDao getAccountDetailDao() {
        return accountDetailDao;
    }

    public EmailDetailDao getEmailDetailDao() {
        return emailDetailDao;
    }

    public AccessoryDetailDao getAccessoryDetailDao() {
        return accessoryDetailDao;
    }

}
